# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [11]:
# write your code here ^_^
seq = np.linspace(0, 10, 15)
seq

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [13]:
# write your code here ^_^
matrix = (np.array([1,2,3,4,5,6,7,8,9,10,11,12]) + 0.1).reshape(2,2,3)
matrix

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [16]:
# write your code here ^_^
type(matrix), matrix.dtype, matrix.shape, matrix.size, matrix.ndim

(numpy.ndarray, dtype('float64'), (2, 2, 3), 12, 3)

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [21]:
# write your code here ^_^
matrix4d = np.reshape(matrix, (1,3,2,2))
matrix4d

array([[[[ 1.1,  2.1],
         [ 3.1,  4.1]],

        [[ 5.1,  6.1],
         [ 7.1,  8.1]],

        [[ 9.1, 10.1],
         [11.1, 12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [24]:
# write your code here ^_^
int_seq = matrix4d.astype(int)
int_seq

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [29]:
# write your code here ^_^
for i in np.nditer(int_seq):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [32]:
# write your code here ^_^
print(int_seq[0, 1, 1, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [34]:
# write your code here ^_^
print(int_seq[0, 1, 0])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [39]:
# write your code here ^_^
np.where(int_seq == 8)

(array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [43]:
# np.array([[[ 1, 2],
#             [ 3,  4],
#             [ 5,  6]],

#            [[ 7,  8],
#             [ 9, 10],
#             [11, 12]]]).shape

(2, 3, 2)

In [46]:
# write your code here ^_^
int_seq = int_seq.reshape(2,3,2)
int_seq

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [47]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
np.concatenate((arr1, arr2))

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [48]:
# write your code here ^_^
np.concatenate((arr1, arr2), axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [52]:
# write your code here ^_^
try:
    np.split(np.concatenate((arr1,arr2), axis=1), 4)
except ValueError as e:
    print(e)

array split does not result in an equal division
