In [89]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [90]:
# write your code here ^_^
x = np.ones((3, 3))
x


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [91]:
# write your code here ^_^
y = np.zeros((3, 3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [92]:
# write your code here ^_^
z = x + y
z

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [93]:
# write your code here ^_^
f'dimensions of x: {x.ndim} | Shape of x: {x.shape} | Size of x: {x.size} | Data type of x: {x.dtype}'

'dimensions of x: 2 | Shape of x: (3, 3) | Size of x: 9 | Data type of x: float64'

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [94]:
# write your code here ^_^
w = np.array([[11, 13], 
              [13, 14], 
              [15 , 16]])
w

array([[11, 13],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [95]:
# write your code here ^_^
z = np.arange(1, 4)
z, z.shape , z.T.shape

(array([1, 2, 3]), (3,), (3,))

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [96]:
# write your code here ^_^
newArray = np.hstack((z.reshape(3,1), w))
newArray


array([[ 1, 11, 13],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [117]:
# write your code here ^_^
for i in np.nditer(newArray):
    print(i)

0
1
2
10
12
14
12
13
15


## Q#9: Reverse the columns and rows of "newArray".

In [98]:
# write your code here ^_^
newArray = newArray.T
newArray

array([[ 1,  2,  3],
       [11, 13, 15],
       [13, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [99]:
# write your code here ^_^
newArray = newArray - 1
newArray

array([[ 0,  1,  2],
       [10, 12, 14],
       [12, 13, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [103]:
# write your code here ^_^
f'Smallest element in newArray: {newArray.min()} | Largest element in newArray: {newArray.max()}'

'Smallest element in newArray: 0 | Largest element in newArray: 15'

## Q#12: Print the first row of "newArray" using indexing.

In [104]:
# write your code here ^_^
print(newArray[0])

[0 1 2]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [105]:
# write your code here ^_^
print(newArray[2,0])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [110]:
# write your code here ^_^
print(newArray[0,0] , newArray[2,1])

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [114]:
# write your code here ^_^
newArray = newArray.reshape(9,1)
newArray

array([[ 0],
       [ 1],
       [ 2],
       [10],
       [12],
       [14],
       [12],
       [13],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [116]:
# write your code here ^_^
try:
    newArray = newArray.reshape(3,2)
except:
    print('Cannot reshape array of size 9 into shape (3,2)')


Cannot reshape array of size 9 into shape (3,2)


# Well Done 🎉